onchain-oracle
Instadapp/dsa-resolvers pull request #54
Opened 2022-02-06 17:12 UTC by CodeNinja04

2022-02-08 20:37 UTC, Vaibhav20201 requested changes

2022-02-08 20:37 UTC, Vaibhav20201 commented on contracts/protocols/mainnet/onchain-oracle/main.sol
> +function getRateInUsdc(IERC20[] memory srctokens) public view returns(uint256[] memory){
take address list as parameter

2022-02-08 20:37 UTC, Vaibhav20201 commented on contracts/protocols/mainnet/onchain-oracle/main.sol
> +function getWrappedTokens(IERC20 wtoken,bool useWrapper) public view returns(IERC20[] memory){
Whats this function? What does it do?

2022-02-08 20:37 UTC, Vaibhav20201 commented on contracts/protocols/mainnet/onchain-oracle/main.sol
> +function oracles() public view returns(IOracle[] memory allOracles) {
What does this function do?

2022-02-08 20:37 UTC, Vaibhav20201 commented on contracts/protocols/mainnet/onchain-oracle/interfaces.sol
> +interface Ofchain {
name this 1inchOracleInterface

2022-02-08 20:37 UTC, Vaibhav20201 commented on contracts/protocols/mainnet/onchain-oracle/main.sol
> +    Ofchain token  = getMainnetoracle();
Define the oracle as a storage/state variable and use it everywhere

2022-02-08 20:37 UTC, Vaibhav20201 commented on contracts/protocols/mainnet/onchain-oracle/interfaces.sol
> +interface IERC20 {
Use import IERC20 interface directly for openzepplin's library

2022-02-08 20:37 UTC, Vaibhav20201 commented on contracts/protocols/mainnet/onchain-oracle/main.sol
> +uint256 ans;
Indent all variables and functions properly

2022-02-08 20:37 UTC, Vaibhav20201 commented on contracts/protocols/mainnet/onchain-oracle/helper.sol
> +}
Define all these as state/storage variables in the core contract and use it. No need of these functions.

2022-02-08 20:37 UTC, Vaibhav20201 commented on contracts/protocols/mainnet/onchain-oracle/main.sol
> +
here

2022-03-13 16:03 UTC, thrilok209 commented
@Vaibhav20201 @CodeNinja04 What's the status on this? Ready to deploy and merge it?

2022-03-13 17:19 UTC, thrilok209 commented
Closing this for now. Can revisit whenever it's required.

2022-03-13 17:19 UTC, closed without merging